apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/configmaps: {{ include (print $.Template.BasePath "/configmaps.yaml") . | sha256sum }}
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccount: {{ include "chart.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            allowPrivilegeEscalation: false
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.proxy.enabled }}
          env:
            - name: HTTP_PROXY
              value: {{ .Values.proxy.http_proxy }}
            - name: HTTPS_PROXY
              value: {{ .Values.proxy.https_proxy }}
            - name: NO_PROXY
              value: {{ .Values.proxy.no_proxy }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: {{ include "chart.fullname" . }}-config
            mountPath: "/app/config"
      volumes:
      - name: {{ include "chart.fullname" . }}-config
        configMap:
          name: {{ include "chart.fullname" . }}-config
