apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-config
  labels:
    {{- include "chart.labels" . | nindent 4 }}
stringData:
  config.yaml: |
    {{ toYaml .Values.config | nindent 4 }}
