# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## @section General
#
## @param serviceAccount.create defaults to true. Please do not change this.
#
## @param image.repository image repository to pull the image from.
## @param image.pullPolicy image pull policy for container
## @param image.tag image tag to use. Defaults to app version (recommended).
#
## @param resources.limits.cpu CPU limits for container.
## @param resources.limits.memory Memory limits for container.
## @param resources.requests.cpu CPU request for container.
## @param resources.requests.memory Memory requests for container.

serviceAccount:
  create: true

image:
  repository: lsdtrip/sauron-collector
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

resources: 
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

## @section Proxy
#
## @param proxy.enabled If the Collector will be running behind a proxy, enable this.
## @param proxy.http_proxy Proxy to use for http requests.
## @param proxy.https_proxy Proxy to use for https requests.
## @param proxy.no_proxy Requests that should avoid using the proxy.

proxy:
  enabled: false
  http_proxy: ""
  https_proxy: ""
  no_proxy: ""

## @section Config
#
## @param config.cluster.name NB - Name of the cluster that the Collector will announce.
## @param config.receiver.url URL of Receiver.
## @param config.receiver.port Port of Receiver.
## @param config.receiver.client_id Client ID to authenticate to Receiver.
## @param config.receiver.client_secret Client Secret to authenticate to Receiver.
## @param config.log.level Log level of Collector. Defaults to `error`.
## @param config.log.console Type of output. Defaults to structured logging if `false`.

## @section Collection Metrics
#
## @param config.collect.version.enabled Enable the collection of cluster version.
## @param config.collect.version.cron Default cron schedule to collect version.
## @param config.collect.deprecations.enabled Enable the collection of cluster deprecations.
## @param config.collect.deprecations.cron Default cron schedule to collect deprecations.
## @param config.collect.nodes.enabled Enable the collection of cluster nodes.
## @param config.collect.nodes.cron Default cron schedule to collect nodes.
## @param config.collect.heartbeat.enabled Enable the sending of cluster heartbeat.
## @param config.collect.heartbeat.cron Default cron schedule to send heartbeat.

config:
  cluster:
    name: ""
  collect:
    version:
      enabled: true
      cron: "0 4 * * *"
    deprecations:
      enabled: true
      cron: "0 5 * * *"
    nodes:
      enabled: true
      cron: "0 * * * *"
    heartbeat:
      enabled: true
      cron: "*/5 * * * *"
  receiver:
    url: ""
    port: "443"
    client_id: ""
    client_secret: ""
  log:
    level: error
    console: false # Defaults to structured if false
