# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: lsdtrip/sauron-collector
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

nameOverride: ""
fullnameOverride: ""

resources: 
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

config:
  cluster:
    name: ""
  receiver:
    url: ""
    port: "443"
    client_id: ""
    client_secret: ""
  log:
    level: error
    console: false # Defaults to structured if false
